
CREATE FUNCTION [Chronological].[DateIsInNextWeek] (
	@date DATE
)
RETURNS BIT AS
BEGIN	
	RETURN CASE
		WHEN DATEPART(WEEK, @date) = DATEPART(WEEK, DATEADD(WEEK, 1, GETDATE())) THEN 1 
		ELSE 0 
	END
END